require('dotenv').config(); // Loads variables from .env
const express = require('express');
const SpotifyWebApi = require('spotify-web-api-node');
const path = require('path');
const app = express();

// Initialize the Spotify API with Environment Variables
const spotifyApi = new SpotifyWebApi({
  clientId: process.env.SPOTIFY_CLIENT_ID,
  clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
  redirectUri: process.env.REDIRECT_URI
});

// Serve the index.html file when someone visits http://localhost:3000
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

app.get('/login', (req, res) => {
  const scopes = ['playlist-modify-public', 'user-read-private'];
  res.redirect(spotifyApi.createAuthorizeURL(scopes));
});

app.get('/callback', async (req, res) => {
  const { code } = req.query;
  try {
    const data = await spotifyApi.authorizationCodeGrant(code);
    spotifyApi.setAccessToken(data.body['access_token']);
    res.send('Login Successful! You can now close this and use the app.');
  } catch (err) {
    console.error('Login Error:', err);
    res.send('Error during login');
  }
});

app.get('/generate-playlist', async (req, res) => {
  const { genre, mood, bpm, decade } = req.query;

  try {
    let targetValence = 0.5;
    if (mood === 'happy') targetValence = 0.8;
    if (mood === 'chill') targetValence = 0.3;

    const recommendations = await spotifyApi.getRecommendations({
      seed_genres: [genre || 'pop'],
      target_tempo: bpm || 120,
      target_valence: targetValence,
      limit: 20
    });

    const trackUris = recommendations.body.tracks.map(t => t.uri);

    const playlist = await spotifyApi.createPlaylist('My AI Hits', { 
      'description': 'Generated by my web app', 
      'public': true 
    });
    
    await spotifyApi.addTracksToPlaylist(playlist.body.id, trackUris);

    res.json({ success: true, url: playlist.body.external_urls.spotify });
  } catch (err) {
    console.error('Generation Error:', err);
    res.status(500).json({ error: err.message });
  }
});

// Start the server using the PORT from .env (or 3000 as a backup)
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`));